@plr = player()


@hero = associative_array(
            'name': '§0S§4u§0p§4e§0r§4b§0o§4y§0(N52)',
            'class': 'superboynew52',
            'sig': 'v0LP0sFc+A87jeXoKSP1mms/xePORXm0KZT1AEZr3GPDAG1BCL/p+V8WjQ/KxObRU6W9+xb5F6vrf3l2Tf7heeycQdxGwBJMwXod6AICk9TEFfY6UDXf1mHWi2jT8x16bMSmwmDryzc3Rcp33qrGXGtlu3ylyDmcNtOms09V+sNe6Dc9KwjjknuaEs/ACtrb3EKkkQidcdiTgHOoG9Svf8BNHC+L+lbPnbu5QYzpQWvB2Z6wpyeNPdBDeYoIvPx6KkbUTQeThm3qmG4TaCfA/6Y52Ib8UPOGWOf7dKyTthF7j9iQYXLC0GX33WL6VeoMXclb1xNZhEvFPgChYhGT5ZKeTW8KSfPmwGPp4eCcguBA6CYrLdkPDNpM6QSktUqV0veiQofgE7i5VI9uYEqLcNcU+EjUnfUKyWb9pfI4GokB7HamPkA0jWpec0ar0RDinzcDBZR8L45R07TiG5m4NFZTa95dGRJoUqv4XEa9hFUPY86rThC+5asKmxS1md0vxLzhnckt2dlrA9F3N72tcFoImD+UbNn+iTuwQ7Tz2cAgU0mdCKgl36oUhJL2HMVqE9tgmRpM9wvDeHPAnGeJw3DVJkAVRn0HWIm6heSUsTmMn5pv2tRtVDVlMgzj+yBR6QI3P/YHduhShLuREx2Q0v9Kx7BFNKxGHEAITOhOEx8=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MTc3MDAzNzk3NDgsInByb2ZpbGVJZCI6IjhjYTdmYzU2NjE0YjQ4MmE5MWRmYmY4NTgwYmEyNzNkIiwicHJvZmlsZU5hbWUiOiJUaGVMaWdodFNoYWRvd18iLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzFjZDRlZGRjMTg2MTRhZGY2NjVmM2UyNGIyOTVhYmExYjI1ZTg0Mjc5MzdjNTc3NzQzOTFmZTZhOTE2YjFhMyJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "I am the cloned son of the son of Krypton!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/run 0-8",
                "/haste 0-8",
                "/fly"
               
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 19 true",
                "/effect ". @plr ." 10 9999 1 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 21 9999 14 true",
                "/shot give ". @plr ." kryptonianlaservision",
                "/give ". @plr ." minecraft:iron_boots 1 8:30 4:30 name:&9W&1a&9ter_Ru&1nn&9ing_&4B&eoo&4ts"                
            )
        )
